version: "3"

services:
  f1virtual:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/data:/app/app/data
    restart: always
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=production
